services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./mockdata:/dataset
      - ./database/:/docker-entrypoint-initdb.d 
    networks:
      - lab2
  
  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_JARS_IVY=/tmp/.ivy2
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src:/opt/spark-app
      - ./jars:/opt/jars
      
    networks:
      - lab2
    
  spark-worker:
    image: bitnami/spark:3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=yes
    depends_on:
      - spark-master
    volumes:
      - ./src:/opt/spark-app
      - ./jars:/opt/jars
    networks:
      - lab2
  
  clickhouse:
  #   image: clickhouse/clickhouse-server:latest
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #     - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/custom.xml
  # clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - lab2

volumes:
  pgdata:
  clickhouse_data:

networks:
  lab2:
    driver: bridge
