version: '3.8'

services:
  db:
    image: postgres:14.8-alpine3.18
    container_name: BGlab1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BGlab1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 

volumes:
  pgdata:

